name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get signing keystore from secrets
        uses: timheuer/base64-to-file@v1.1
        id: keystore
        with:
          fileName: 'wowbagger-app.jks'
          encodedString: ${{ secrets.SIGN_KEY }}

      - name: Create keystore.properties
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './keystore.properties'
          property: |
            storeFile
            storePassword
            keyPassword
            alias
          value: |
            ${{ steps.keystore.outputs.filePath }}
            ${{ secrets.STORE_KEY_PASSWORD }}
            ${{ secrets.KEY_PASSWORD }}
            ${{ secrets.ALIAS }}

      - name: LS
        run: ls -al

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
