name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get signing keystore from secrets
        uses: timheuer/base64-to-file@v1.1
        id: keystore
        with:
          fileName: 'wowbagger-app.jks'
          encodedString: ${{ secrets.SIGN_KEY }}

      - name: Create keystore.properties
        run: |
          echo "storeFile=${{ steps.keystore.outputs.filePath }}" > ./keystore.properties
          echo "storePassword=${{ secrets.STORE_KEY_PASSWORD }}" >> ./keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> ./keystore.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> ./keystore.properties

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build bundleRelease

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml

      - name: GitHub Action for Android Lint
        uses: yutailang0119/action-android-lint@v2.0.0
        if: always()
        with:
          report-path: build/reports/*.xml

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            app/build/outputs/bundle/release/app-release.aab
          # app/build/outputs/mapping/release/mapping.txt
          fail_on_unmatched_files: true
          generate_release_notes: true
