name: CI

on:
  push:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Build Release AAB
        if: github.ref == 'refs/heads/main'
        run: ./gradlew bundleRelease

      - uses: r0adkll/sign-android-release@v1
        if: github.ref == 'refs/heads/main'
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGN_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
