name: CI

on:
  push:

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
