name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get signing keystore from secrets
        uses: timheuer/base64-to-file@v1.1
        id: keystore
        with:
          fileName: 'wowbagger-app.jks'
          encodedString: ${{ secrets.SIGN_KEY }}

      - name: Create keystore.properties
        run: |
          echo "storeFile=${{ steps.keystore.outputs.filePath }}" > ./keystore.properties
          echo "storePassword=${{ secrets.STORE_KEY_PASSWORD }}" >> ./keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> ./keystore.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> ./keystore.properties

      - name: Build app
        uses: gradle/gradle-build-action@v2.2.0
        with:
          arguments: clean build assemble assembleAndroidTest bundle

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.37
        if: always()
        with:
          files: ./app/build/test-results/**/*.xml
          comment_mode: off

      - name: GitHub Action for Android Lint
        uses: yutailang0119/action-android-lint@v3.0.0
        if: always()
        with:
          report-path: ./app/build/reports/lint-results-debug.xml

      - name: Cloud SDK auth
        uses: google-github-actions/auth@v0.8.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run instrumented tests
        run: |
          gcloud firebase test android run \
          --type instrumentation --use-orchestrator \
          --app app/build/outputs/apk/debug/app-debug.apk \
          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          --device model=Nexus4,version=21,locale=de,orientation=portrait  \
          --device model=heroqlteue,version=26,locale=en,orientation=portrait \
          --device model=Pixel3,version=30,locale=de,orientation=landscape

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          files: |
            app/build/outputs/bundle/release/app-release.aab
          fail_on_unmatched_files: true
          generate_release_notes: true

      - uses: r0adkll/upload-google-play@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          serviceAccountJsonPlainText: ${{ secrets.GCP_SA_KEY }}
          packageName: com.github.notizklotz.swisswowbagger.app
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          status: completed
