name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build bundleRelease

      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGN_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            ${{steps.sign_app.outputs.signedReleaseFile}}
            app/build/outputs/mapping/release/mapping.txt
          generate_release_notes: true
