name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGN_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: GH Release
      
      - uses: softprops/action-gh-release@v0.1
        with:
          prerelease: true
          # Newline-delimited list of path globs for asset files to upload
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          # Fails if any of the `files` globs match nothing. Defaults to false
          fail_on_unmatched_files: true
          generate_release_notes: true
