name: Scan with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
